//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsThisYear.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CarsThisYearContextContainer : DbContext
    {
        public CarsThisYearContextContainer()
            : base("name=CarsThisYearContextContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Make> Makes { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<ModelSeries> ModelSeries { get; set; }
        public virtual DbSet<ModelStyle> ModelStyles { get; set; }
        public virtual DbSet<Engine> Engines { get; set; }
        public virtual DbSet<Drivetrain> Drivetrains { get; set; }
        public virtual DbSet<Transmission> Transmissions { get; set; }
        public virtual DbSet<ModelColor> ModelColors { get; set; }
        public virtual DbSet<GeneralColor> GeneralColors { get; set; }
        public virtual DbSet<GeneralTransmission> GeneralTransmissions { get; set; }
        public virtual DbSet<GeneralDrivetrain> GeneralDrivetrains { get; set; }
        public virtual DbSet<GeneralEngine> GeneralEngines { get; set; }
    }
}
