//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsThisYear.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Make
    {
        public Make()
        {
            this.Models = new HashSet<Model>();
            this.Engines = new HashSet<Engine>();
            this.Drivetrains = new HashSet<Drivetrain>();
            this.Transmissions = new HashSet<Transmission>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Model> Models { get; set; }
        public virtual ICollection<Engine> Engines { get; set; }
        public virtual ICollection<Drivetrain> Drivetrains { get; set; }
        public virtual ICollection<Transmission> Transmissions { get; set; }
    }
}
