//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsThisYear.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelColor
    {
        public ModelColor()
        {
            this.ModelStyles = new HashSet<ModelStyle>();
            this.GeneralColors = new HashSet<GeneralColor>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ModelStyle> ModelStyles { get; set; }
        public virtual ICollection<GeneralColor> GeneralColors { get; set; }
    }
}
