//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsThisYear.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelStyle
    {
        public ModelStyle()
        {
            this.Engines = new HashSet<Engine>();
            this.Transmissions = new HashSet<Transmission>();
            this.Drivetrains = new HashSet<Drivetrain>();
            this.ModelColors = new HashSet<ModelColor>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ModelSeriesId { get; set; }
    
        public virtual ICollection<Engine> Engines { get; set; }
        public virtual ICollection<Transmission> Transmissions { get; set; }
        public virtual ICollection<Drivetrain> Drivetrains { get; set; }
        public virtual ICollection<ModelColor> ModelColors { get; set; }
        public virtual ModelSeries ModelSery { get; set; }
    }
}
