//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsThisYear.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transmission
    {
        public Transmission()
        {
            this.Makes = new HashSet<Make>();
            this.GeneralTransmissions = new HashSet<GeneralTransmission>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int ModelStyleId { get; set; }
    
        public virtual ModelStyle ModelStyle { get; set; }
        public virtual ICollection<Make> Makes { get; set; }
        public virtual ICollection<GeneralTransmission> GeneralTransmissions { get; set; }
    }
}
